import XCTest
@testable import AlphaFingerKit

/// Drives the whole application pipeline end to end without hardware: grouping,
/// debouncing, classification, naming and routing, over a scripted session built
/// by `SyntheticRing`.
///
/// The session is generated rather than recorded, so it holds no real device
/// identifier and no real audio, and it can be regenerated by anyone. The
/// encoder that produces it is checked against the decoder by
/// `testRiceRoundTrip`, so the fixtures cannot quietly drift into nonsense.
/// Collects the sizes a file was observed at while it was being written.
private final class ObservedSizes: @unchecked Sendable {
  private var seen: [String: Set<Int>] = [:]
  private let lock = NSLock()
  var stopped = false

  func record(name: String, size: Int) {
    lock.lock(); defer { lock.unlock() }
    seen[name, default: []].insert(size)
  }

  func sizes(for name: String) -> Set<Int> {
    lock.lock(); defer { lock.unlock() }
    return seen[name] ?? []
  }
}

final class PipelineTests: XCTestCase {
  private var blobs: URL!
  private var workspace: URL!

  /// The scripted session, in the order the ring would have produced it:
  /// a plain recording, a tap-then-record, a lone tap, then a double tap.
  ///
  /// `swingUtc` is one second behind the timestamp that comes out, because the
  /// ring's time is `utc + correction + 1` and no correction record is present.
  private static let session: [(index: UInt32, bytes: [UInt8])] = {
    var parts: [(UInt32, [UInt8])] = []
    // Recording A - a long press, no tap before it. 09:08:03Z.
    for (offset, index) in [UInt32(0), 1, 2].enumerated() {
      parts.append((index, SyntheticRing.part(
        startIndex: 0, isMultiPart: true, isFinalPart: index == 2,
        pressSequence: 0x1, pressCount: 1, unixTime: 1_787_476_082,
        samples: 900, seed: Double(offset))))
    }
    // Recording B - short then long: a tap, then a recording. 09:08:27Z.
    for (offset, index) in [UInt32(3), 4].enumerated() {
      parts.append((index, SyntheticRing.part(
        startIndex: 3, isMultiPart: true, isFinalPart: index == 4,
        pressSequence: 0x2, pressCount: 2, unixTime: 1_787_476_106,
        samples: 700, seed: Double(offset) + 10)))
    }
    // A lone tap, then a double tap. Deliberately NOT adjacent indices:
    // `GestureDebouncer.belongTogether` treats consecutive indices as one burst
    // whatever the clock says, so 5 and 6 would merge into a single 2-tap. Ten
    // seconds apart as well, and both recent enough not to be dropped as stale.
    parts.append((5, SyntheticRing.part(
      startIndex: 5, isMultiPart: false, isFinalPart: true,
      pressSequence: 0x0, pressCount: 1, unixTime: 1_787_476_128, samples: 0)))
    parts.append((8, SyntheticRing.part(
      startIndex: 8, isMultiPart: false, isFinalPart: true,
      pressSequence: 0x0, pressCount: 2, unixTime: 1_787_476_138, samples: 0)))
    return parts.map { (index: $0.0, bytes: $0.1) }
  }()

  override func setUpWithError() throws {
    blobs = FileManager.default.temporaryDirectory
      .appendingPathComponent("alphafinger-blobs-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: blobs, withIntermediateDirectories: true)
    for part in Self.session {
      let name = String(format: "collection-%03d.bin", part.index)
      try Data(part.bytes).write(to: blobs.appendingPathComponent(name))
    }

    workspace = FileManager.default.temporaryDirectory
      .appendingPathComponent("alphafinger-pipeline-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: workspace, withIntermediateDirectories: true)
  }

  override func tearDownWithError() throws {
    try? FileManager.default.removeItem(at: workspace)
    try? FileManager.default.removeItem(at: blobs)
  }

  private struct Run {
    var recordings: [String] = []
    var doubleTapRecordings: [String] = []
    var commands: [String] = []
    var failures: [String] = []
    var resets: [String] = []
  }

  /// `markerFile` lets the shell command prove it actually ran.
  private func drive(startingAfter: UInt32? = nil,
                     cursor: CollectionCursor? = nil) throws -> Run {

    let recordings = workspace.appendingPathComponent("recordings", isDirectory: true)
    let marker = workspace.appendingPathComponent("commands.log")

    var settings = RingPipelineSettings(
      recordingsDirectory: recordings)
    // One command for everything, recording what fired from the environment
    // alone -- which is all a real script has to go on.
    settings.command = "echo $ALPHAFINGER_GESTURE:$ALPHAFINGER_TAP_COUNT:"
      + "${ALPHAFINGER_FILE+file}:${ALPHAFINGER_PRESS_PATTERN+pattern} "
      + ">> \(marker.path)"

    // The capture is from 2026-08-23; anchor "now" to it or the staleness rule
    // would discard every gesture as ancient.
    let captureTime = Date(timeIntervalSince1970: 1_787_476_150)
    let pipeline = RingPipeline(settings: settings, cursor: cursor,
                                now: { captureTime })

    var run = Run()
    pipeline.onOutcome = { outcome in
      switch outcome {
      case let .savedRecording(result, isDoubleTap, _, _):
        if isDoubleTap { run.doubleTapRecordings.append(result.audioURL.lastPathComponent) }
        else { run.recordings.append(result.audioURL.lastPathComponent) }
      case let .ranCommand(outcome, label, _):
        run.commands.append("\(label):\(outcome.exitCode)")
      case .ignored, .detail, .startedCommand:
        break
      case let .ringReset(reason):
        run.resets.append(reason)
      case let .failed(message):
        run.failures.append(message)
      }
    }

    let source = ReplayRingSource(blobDirectory: blobs, startingAfterIndex: startingAfter)
    source.onCollection = { pipeline.accept($0) }
    source.onError = { run.failures.append(String(describing: $0)) }
    source.start()
    pipeline.finish()
    // Commands run on their own queue now, so their outcomes are still in flight
    // when `finish()` returns. Without this the assertions below race them.
    pipeline.waitForCommands()
    return run
  }

  /// The scripted session: a recording, a tap-then-record, a lone tap, a double tap.
  func testRoutesTheCapturedSessionCorrectly() throws {
    let run = try drive()
    XCTAssertEqual(run.failures, [], "pipeline reported failures")

    XCTAssertEqual(run.recordings.count, 1, "expected one plain recording")
    XCTAssertEqual(run.doubleTapRecordings.count, 1, "expected one double-tap recording")

    XCTAssertTrue(run.commands.contains("2-tap:0"),
                  "double tap should have run its command; got \(run.commands)")
    XCTAssertTrue(run.commands.contains("1-tap:0"),
                  "single tap should have run its command; got \(run.commands)")
  }

  /// The ring's clock is the only source of recording time, and it is what the
  /// filename has to carry.
  func testFilenamesCarryTheRingTimestamp() throws {
    let run = try drive()
    // utc + (int32)correction + 1; the 0xFFFFFFFF sentinel is -1, cancelling the +1.
    XCTAssertEqual(run.recordings.first?.hasPrefix("2026-08-23T090803Z"), true,
                   "plain recording filename was \(run.recordings)")
    XCTAssertEqual(run.doubleTapRecordings.first?.hasPrefix("2026-08-23T090827Z"), true,
                   "double-tap recording filename was \(run.doubleTapRecordings)")
  }

  /// A sidecar makes an archived folder self-describing.
  func testSidecarDescribesTheRecording() throws {
    _ = try drive()
    let directory = workspace.appendingPathComponent("recordings")
    let sidecars = try FileManager.default
      .contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
      .filter { $0.pathExtension == "json" }
      .sorted { $0.lastPathComponent < $1.lastPathComponent }
    // One folder now holds both: the plain recording and the tap-then-record. The
    // gesture is in the filename rather than the directory.
    XCTAssertEqual(sidecars.count, 2)
    let names = sidecars.map(\.lastPathComponent)
    XCTAssertEqual(Set(names).count, 2, "filenames collided: \(names)")
    XCTAssertTrue(names.contains { $0.contains("-tap0-") },
                  "expected a plain recording, got \(names)")
    XCTAssertTrue(names.contains { $0.contains("-tap1-") },
                  "expected a tap-then-record, got \(names)")

    let json = try JSONSerialization.jsonObject(with: Data(contentsOf: sidecars[0]))
    let metadata = try XCTUnwrap(json as? [String: Any])
    XCTAssertEqual(metadata["gesture"] as? String, "recording")
    // The ring stated it: one long press, no taps.
    XCTAssertEqual(metadata["pressPattern"] as? String, "long")
    XCTAssertEqual(metadata["classifiedBy"] as? String, "pressRecord")
    XCTAssertNotNil(metadata["ageAtReceiptSeconds"])
    XCTAssertEqual(metadata["isMultiPart"] as? Bool, true)
    XCTAssertEqual(metadata["sampleRateHz"] as? Int, 9997)
    XCTAssertEqual(metadata["ringTimestamp"] as? String, "2026-08-23T09:08:03Z")
    // Three parts of 900 samples at 9997 Hz.
    XCTAssertEqual((metadata["collectionIndices"] as? [Int])?.count, 3)
    XCTAssertEqual(metadata["durationSeconds"] as? Double ?? 0, 0.27, accuracy: 0.01)
  }

  /// A double tap arrives as one collection reporting two presses. Acting on the
  /// first press would fire a single-tap action every time someone double taps.
  func testDoubleTapIsDebouncedIntoOneGesture() throws {
    let run = try drive()
    let doubles = run.commands.filter { $0.hasPrefix("2-tap") }
    let singles = run.commands.filter { $0.hasPrefix("1-tap") }
    XCTAssertEqual(doubles.count, 1, "the double tap must fire exactly once")
    // Only the lone tap fires single-tap; the double tap reports its own count.
    XCTAssertEqual(singles.count, 1, "only the standalone tap should fire single-tap")
  }

  /// The one command runs for recordings, and gets the recording variables.
  func testTheCommandRunsForRecordings() throws {
    _ = try drive()
    let log = workspace.appendingPathComponent("commands.log")
    let text = try String(contentsOf: log, encoding: .utf8)
    // One plain recording (no preceding tap) and one preceded by a tap.
    XCTAssertTrue(text.contains("recording:0:file:pattern"),
                  "expected plain recording; got:\n\(text)")
    XCTAssertTrue(text.contains("recording:1:file:pattern"),
                  "expected tap-then-record, TAP_COUNT 1; got:\n\(text)")
  }

  /// A tap must be told where things go. It has no file to take a folder from,
  /// and this is the only way it can write anything sensible.
  func testATapIsToldWhereRecordingsGo() throws {
    let dumps = workspace.appendingPathComponent("env", isDirectory: true)
    try FileManager.default.createDirectory(at: dumps, withIntermediateDirectories: true)
    let recordings = workspace.appendingPathComponent("recordings")
    var settings = RingPipelineSettings(recordingsDirectory: recordings)
    settings.command = "env | grep '^ALPHAFINGER_' | sort > "
      + "\(dumps.path)/$ALPHAFINGER_GESTURE"

    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()

    let taps = try FileManager.default.contentsOfDirectory(atPath: dumps.path)
      .filter { $0.hasSuffix("-tap") }
    XCTAssertFalse(taps.isEmpty, "no tap ran a command")
    for tap in taps {
      let text = try String(contentsOf: dumps.appendingPathComponent(tap),
                            encoding: .utf8)
      XCTAssertTrue(text.contains("ALPHAFINGER_RECORDINGS_DIR=\(recordings.path)"),
                    "a tap was not told the recordings folder: \(text)")
      XCTAssertFalse(text.contains("ALPHAFINGER_FILE="),
                     "a tap must still carry no recording variables")
    }
  }

  /// The battery reading has to reach a command, and must be absent rather than
  /// invented when the ring gave none.
  func testBatteryReachesTheCommandOnlyWhenTheRingReportedIt() {
    let group = CollectionGroup(startIndex: 4, collections: [])
    XCTAssertNil(group.batteryMilliVolts, "no collections, no reading")

    // The debouncer is what carries it for a gesture, since a gesture has no group
    // left by the time the environment is built.
    var seen: [UInt16?] = []
    let debouncer = GestureDebouncer(now: { Date(timeIntervalSince1970: 1_787_476_150) }) {
      seen.append($0.batteryMilliVolts)
    }
    let when = Date(timeIntervalSince1970: 1_787_476_145)
    debouncer.accept(count: 1, at: when, startIndex: 1, batteryMilliVolts: 1578)
    debouncer.flush()
    debouncer.accept(count: 1, at: when, startIndex: 9, batteryMilliVolts: nil)
    debouncer.flush()
    XCTAssertEqual(seen, [1578, nil])
  }

  // MARK: - Saying when a command starts

  /// A recording used to be followed by several silent seconds and then every
  /// line at once, because nothing was emitted until the command exited. The
  /// start has to be announced before the work happens, not after.
  func testACommandAnnouncesItselfBeforeItFinishes() throws {
    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "sleep 0.3"
    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var order: [String] = []
    var queued: [Double] = []
    pipeline.onOutcome = {
      switch $0 {
      case let .startedCommand(_, _, queuedSeconds):
        order.append("started"); queued.append(queuedSeconds)
      case .ranCommand: order.append("ran")
      default: break
      }
    }
    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()

    XCTAssertFalse(order.isEmpty, "no command ran at all")
    XCTAssertEqual(order.first, "started", "the start must be announced first")
    for (index, label) in order.enumerated() where index.isMultiple(of: 2) {
      XCTAssertEqual(label, "started", "every run must be started then ran: \(order)")
    }
    XCTAssertEqual(queued.first ?? .infinity, 0, accuracy: 0.2,
                   "the first command waits for nothing")
  }

  /// The queue is serial, so the second command's wait must cover the first's run.
  /// That number is the only thing that would tell a slow command apart from one
  /// stuck behind another.
  func testQueuedSecondsCoversTheCommandInFront() throws {
    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "sleep 0.4"
    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var queued: [Double] = []
    pipeline.onOutcome = {
      if case let .startedCommand(_, _, seconds) = $0 { queued.append(seconds) }
    }
    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()

    guard queued.count >= 2 else {
      return XCTFail("expected at least two commands, got \(queued.count)")
    }
    XCTAssertGreaterThanOrEqual(queued[1], 0.4,
                                "the second waited on the first: \(queued)")
  }

  // MARK: - A tap before a recording

  /// The reported bug: tap, then press and hold, and the command ran twice.
  ///
  /// The ring stores the tap as its own collection the moment it ends -- while the
  /// button is still down for the recording -- so it arrives first, on its own.
  /// The recording that follows already reports the tap in its press record, so
  /// acting on both runs the command twice for one gesture. The shared fixture
  /// could not catch this: its tap-then-record is a single group with pressCount 2,
  /// not a separate tap collection.
  private func tapThenRecordBlobs(gapSeconds: UInt32 = 1) throws -> URL {
    let dir = FileManager.default.temporaryDirectory
      .appendingPathComponent("alphafinger-tap-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    // Close to the test's "now" (1_787_476_150). Any older and the debouncer's
    // staleness rule would drop the tap instead of emitting it, and the test would
    // pass whether or not the recording absorbed it.
    let tapTime: UInt32 = 1_787_476_140
    // Index 10: the bare tap. No audio, one short press.
    try Data(SyntheticRing.part(startIndex: 10, isMultiPart: false, isFinalPart: true,
                                pressSequence: 0x0, pressCount: 1,
                                unixTime: tapTime, samples: 0))
      .write(to: dir.appendingPathComponent("collection-010.bin"))
    // Index 11: the recording, its press record carrying the same tap (short+long).
    try Data(SyntheticRing.part(startIndex: 11, isMultiPart: false, isFinalPart: true,
                                pressSequence: 0x2, pressCount: 2,
                                unixTime: tapTime + gapSeconds, samples: 900))
      .write(to: dir.appendingPathComponent("collection-011.bin"))
    return dir
  }

  private func runsFrom(_ dir: URL, endOfBatchBetween: Bool) throws -> [String] {
    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "true"
    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var runs: [String] = []
    pipeline.onOutcome = {
      if case let .ranCommand(_, label, _) = $0 { runs.append(label) }
    }
    let source = ReplayRingSource(blobDirectory: dir)
    var delivered = 0
    source.onCollection = {
      pipeline.accept($0)
      delivered += 1
      // The real case: the tap is drained in one cycle and the recording in the
      // next, because the ring only stores the recording once the button is up.
      if endOfBatchBetween && delivered == 1 { pipeline.endOfBatch() }
    }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()
    return runs
  }

  func testATapAbsorbedByTheRecordingAfterItRunsOnce() throws {
    let runs = try runsFrom(try tapThenRecordBlobs(), endOfBatchBetween: false)
    XCTAssertEqual(runs, ["recording"],
                   "the tap must be absorbed, not run on its own; got \(runs)")
  }

  /// The case from the live log: the two arrive in different drain batches.
  /// `endOfBatch` used to flush the gesture, so the tap fired seconds before the
  /// recording that would have absorbed it existed.
  func testATapHeldAcrossBatchesIsStillAbsorbed() throws {
    let runs = try runsFrom(try tapThenRecordBlobs(), endOfBatchBetween: true)
    XCTAssertEqual(runs, ["recording"],
                   "endOfBatch released the tap early; got \(runs)")
  }

  /// A tap on its own must still fire -- held by `endOfBatch`, released when the
  /// ring reports itself idle.
  func testALoneTapWaitsForTheRingToGoIdle() throws {
    let dir = FileManager.default.temporaryDirectory
      .appendingPathComponent("alphafinger-lone-\(UUID().uuidString)", isDirectory: true)
    try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    try Data(SyntheticRing.part(startIndex: 10, isMultiPart: false, isFinalPart: true,
                                pressSequence: 0x0, pressCount: 1,
                                unixTime: 1_787_476_140, samples: 0))
      .write(to: dir.appendingPathComponent("collection-010.bin"))

    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "true"
    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var runs: [String] = []
    pipeline.onOutcome = {
      if case let .ranCommand(_, label, _) = $0 { runs.append(label) }
    }
    let source = ReplayRingSource(blobDirectory: dir)
    source.onCollection = { pipeline.accept($0) }
    source.start()

    pipeline.endOfBatch()
    pipeline.waitForCommands()
    XCTAssertEqual(runs, [], "a fresh tap must be held in case a recording follows")

    pipeline.ringWentIdle()
    pipeline.waitForCommands()
    XCTAssertEqual(runs, ["1-tap"], "an idle ring means nothing can absorb it now")
  }

  /// Absorption must not swallow a tap that has nothing to do with the recording.
  func testOnlyAnAdjacentRecordingAbsorbsATap() {
    var emitted: [UInt32] = []
    let debouncer = GestureDebouncer(now: { Date(timeIntervalSince1970: 1_787_476_150) }) {
      emitted.append($0.startIndex)
    }
    let when = Date(timeIntervalSince1970: 1_787_476_140)
    debouncer.accept(count: 1, at: when, startIndex: 10)
    XCTAssertFalse(debouncer.discardPending(absorbedBy: 40,
                                            at: when.addingTimeInterval(60)),
                   "a distant recording must not absorb an unrelated tap")
    XCTAssertTrue(debouncer.discardPending(absorbedBy: 11, at: when),
                  "the very next collection is the same burst")
    debouncer.flush()
    XCTAssertEqual(emitted, [], "the absorbed tap must never be emitted")
  }

  /// "recording(s)" reads like a placeholder nobody finished. It appears in the
  /// menu, in notifications and in error messages, so it is worth one function.
  func testCountsReadAsEnglish() {
    XCTAssertEqual(counted(0, "recording"), "0 recordings")
    XCTAssertEqual(counted(1, "recording"), "1 recording")
    XCTAssertEqual(counted(2, "recording"), "2 recordings")
  }

  /// A tap must arrive with none of the recording variables set.
  ///
  /// Not merely unused -- **unset**, so a script can test for `FILE` to know which
  /// of the two it is handling. `${VAR-none}` prints `none` only when the variable
  /// is absent, so this distinguishes unset from empty.
  func testATapCarriesNoRecordingVariables() throws {
    _ = try drive()
    let text = try String(contentsOf: workspace.appendingPathComponent("commands.log"),
                          encoding: .utf8)
    let taps = text.split(separator: "\n").filter { $0.contains("-tap:") }
    XCTAssertFalse(taps.isEmpty, "no tap ran a command; got:\n\(text)")
    for tap in taps {
      // Both recording fields expand to nothing, so the line ends in two empty
      // colon-separated fields. `${VAR+x}` is empty for an unset variable, which
      // is what a tap must give.
      XCTAssertTrue(tap.hasSuffix("::"),
                    "a tap carried recording variables: \(tap)")
    }
  }

  /// Every variable the command description promises, present and non-empty.
  func testRecordingVariablesAreAllSet() throws {
    // One dump per gesture: the same command runs for taps, and a tap arriving
    // last would otherwise overwrite the recording's environment.
    let dumps = workspace.appendingPathComponent("env", isDirectory: true)
    try FileManager.default.createDirectory(at: dumps, withIntermediateDirectories: true)
    let dump = dumps.appendingPathComponent("recording")
    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "env | grep '^ALPHAFINGER_' | sort > "
      + "\(dumps.path)/$ALPHAFINGER_GESTURE"

    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()

    var seen: [String: String] = [:]
    for line in try String(contentsOf: dump, encoding: .utf8).split(separator: "\n") {
      guard let split = line.firstIndex(of: "=") else { continue }
      seen[String(line[line.startIndex..<split])] = String(line[line.index(after: split)...])
    }
    for name in ["ALPHAFINGER_GESTURE", "ALPHAFINGER_TAP_COUNT",
                 "ALPHAFINGER_START_INDEX", "ALPHAFINGER_RECORDINGS_DIR",
                 "ALPHAFINGER_FILE", "ALPHAFINGER_METADATA_FILE",
                 "ALPHAFINGER_PRESS_PATTERN", "ALPHAFINGER_DURATION"] {
      XCTAssertNotNil(seen[name], "\(name) was not set")
      XCTAssertFalse(seen[name]?.isEmpty ?? true, "\(name) was set but empty")
    }
  }

  /// The destination must never contain a partial file, and must never contain
  /// staging debris. Checked by watching the folder while the write happens.
  func testRecordingsAppearAtomically() throws {
    let destination = workspace.appendingPathComponent("atomic", isDirectory: true)
    try FileManager.default.createDirectory(at: destination, withIntermediateDirectories: true)

    // Poll the destination throughout the write and record every state it passes
    // through. A non-atomic writer would be caught with a short .wav present.
    let observed = ObservedSizes()
    let watching = Thread {
      while !observed.stopped {
        if let names = try? FileManager.default.contentsOfDirectory(atPath: destination.path) {
          for name in names where name.hasSuffix(".wav") {
            let path = destination.appendingPathComponent(name).path
            let size = (try? FileManager.default.attributesOfItem(atPath: path)[.size]) as? Int
            observed.record(name: name, size: size ?? 0)
          }
        }
        Thread.sleep(forTimeInterval: 0.001)
      }
    }
    watching.start()

    let source = ReplayRingSource(blobDirectory: blobs)
    var group: CollectionGroup?
    let assembler = CollectionAssembler()
    source.onCollection = { collection in
      if group == nil, let complete = assembler.accept(collection).first { group = complete }
    }
    source.start()
    let recording = try XCTUnwrap(group, "expected at least one complete group")
    let result = try RecordingWriter().write(recording, to: destination, gesture: "recording")
    observed.stopped = true
    Thread.sleep(forTimeInterval: 0.02)

    let finalSize = try XCTUnwrap(
      (try FileManager.default.attributesOfItem(atPath: result.audioURL.path)[.size]) as? Int)
    // Every size the file was ever seen at must be the finished size: it appeared
    // complete or not at all.
    let sizes = observed.sizes(for: result.audioURL.lastPathComponent)
    XCTAssertFalse(sizes.contains { $0 != finalSize },
                   "the .wav was visible at a partial size: saw \(sizes.sorted()), "
                   + "final \(finalSize)")

    // The sidecar lands first, so anything watching for .wav finds it already there.
    XCTAssertTrue(FileManager.default.fileExists(atPath: result.metadataURL.path))

    // No staging directory left behind in the destination.
    let leftovers = try FileManager.default
      .contentsOfDirectory(atPath: destination.path)
      .filter { !$0.hasSuffix(".wav") && !$0.hasSuffix(".json") }
    XCTAssertEqual(leftovers, [], "staging debris left in the destination")
  }

  // MARK: - What a command is promised

  /// A command set after the pipeline was built must still fire.
  ///
  /// The pipeline holds a settings snapshot, and the app only builds one at
  /// launch -- so this is what stands between "typed a command into Settings" and
  /// "the command runs" without relaunching.
  func testACommandSetAfterConstructionIsUsed() throws {
    let marker = workspace.appendingPathComponent("late.log")
    let settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    XCTAssertTrue(settings.command.isEmpty, "starts with none")

    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var ignored: [String] = []
    pipeline.onOutcome = { if case let .ignored(reason) = $0 { ignored.append(reason) } }

    var edited = settings
    edited.command = "echo late > \(marker.path)"
    pipeline.settings = edited

    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()
    pipeline.waitForCommands()

    XCTAssertTrue(FileManager.default.fileExists(atPath: marker.path),
                  "the pipeline used its snapshot instead of the edited settings")
    XCTAssertFalse(ignored.contains { $0.contains("no post-recording command") },
                   "it must not report the command as missing once one is set")
  }

  /// Commands must leave the caller's thread. `accept` is driven from the main
  /// actor, so a command that ran inline froze the whole UI for its duration --
  /// and transcribing a recording takes tens of seconds.
  ///
  /// The command sleeps; if it were still inline, `accept` could not return until
  /// it finished and the marker would already exist.
  func testCommandsDoNotBlockTheCaller() throws {
    let marker = workspace.appendingPathComponent("slow.log")
    var settings = RingPipelineSettings(
      recordingsDirectory: workspace.appendingPathComponent("recordings"))
    settings.command = "sleep 0.4; echo done > \(marker.path)"

    let pipeline = RingPipeline(settings: settings, cursor: nil,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()

    XCTAssertFalse(FileManager.default.fileExists(atPath: marker.path),
                   "the command ran inline -- the caller waited for it")
    pipeline.waitForCommands()
    XCTAssertTrue(FileManager.default.fileExists(atPath: marker.path),
                  "waitForCommands must settle what was dispatched")
  }

  /// A failed write must leave the cursor alone, so the collections are fetched
  /// again rather than silently lost.
  func testCursorDoesNotAdvanceWhenTheWriteFails() throws {
    let cursor = InMemoryCollectionCursor()
    // A destination that cannot be created: a directory path under a regular file.
    let blocker = workspace.appendingPathComponent("not-a-directory")
    try Data("x".utf8).write(to: blocker)

    var settings = RingPipelineSettings(
      recordingsDirectory: blocker.appendingPathComponent("nope"))
    let pipeline = RingPipeline(settings: settings, cursor: cursor,
                                now: { Date(timeIntervalSince1970: 1_787_476_150) })
    var failures = 0
    pipeline.onOutcome = { if case .failed = $0 { failures += 1 } }

    let source = ReplayRingSource(blobDirectory: blobs)
    source.onCollection = { pipeline.accept($0) }
    source.start()
    pipeline.finish()

    XCTAssertGreaterThan(failures, 0, "the write should have failed")
    XCTAssertNil(cursor.lastCompletedIndex,
                 "a failed write must not advance the cursor")
  }

  /// Nothing should be filed twice; the cursor is what prevents it.
  func testIndexCursorMakesReplayIdempotent() throws {
    let store = InMemoryCollectionCursor()
    let first = try drive(cursor: store)
    XCTAssertEqual(first.recordings.count + first.doubleTapRecordings.count, 2)

    let second = try drive(cursor: store)
    XCTAssertEqual(second.recordings.count, 0, "replay refiled a recording")
    XCTAssertEqual(second.doubleTapRecordings.count, 0, "replay refiled a recording")
  }

  /// Two recordings that produce the same filename must both survive.
  ///
  /// The ring's timestamp has 1-second resolution, so collisions are possible; and
  /// when a run was being split per collection every fragment carried the same
  /// start index, so they overwrote each other and the audio was lost. Filing the
  /// same capture twice reproduces the collision exactly.
  func testCollidingFilenamesDoNotOverwrite() throws {
    _ = try drive(cursor: InMemoryCollectionCursor())
    let directory = workspace.appendingPathComponent("recordings")
    let first = try FileManager.default
      .contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
      .filter { $0.pathExtension == "wav" }
    XCTAssertEqual(first.count, 2)

    // A fresh cursor refiles the same recordings, so every stem collides.
    _ = try drive(cursor: InMemoryCollectionCursor())
    let second = try FileManager.default
      .contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
      .filter { $0.pathExtension == "wav" }
    XCTAssertEqual(second.count, 4,
                   "refiling overwrote instead of suffixing: \(second.map(\.lastPathComponent))")
    XCTAssertEqual(Set(second.map(\.lastPathComponent)).count, 4)
  }

  /// The bug a ring reset causes, end to end.
  ///
  /// A cursor left over from before a reset marks every new index as already
  /// seen, so the client fetches nothing and looks perfectly healthy. This drives
  /// the real capture with a poisoned cursor to prove the failure, then
  /// invalidates and proves recovery.
  func testResetInvalidatesTheCursorAndRefetches() throws {
    let store = InMemoryCollectionCursor()
    // Far past every index in the capture: exactly what a pre-reset cursor looks
    // like once the ring restarts its numbering at 0.
    try store.markCompleted(throughIndex: 100_000)

    let poisoned = try drive(cursor: store)
    XCTAssertEqual(poisoned.recordings.count + poisoned.doubleTapRecordings.count, 0,
                   "this is the silent failure: a stale cursor hides everything")

    try store.invalidate(reason: "collection window fell below the cursor")
    let recovered = try drive(cursor: store)
    XCTAssertEqual(recovered.recordings.count + recovered.doubleTapRecordings.count, 2,
                   "after invalidating, every recording must be filed again")
  }
}
